backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "produk"
    label: "Produk"
    folder: "produk"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama", name: "nama", widget: "string" }
      - { label: "Deskripsi", name: "deskripsi", widget: "text" }
      - { label: "Harga", name: "harga", widget: "number" }
      - { label: "Gambar", name: "gambar", widget: "image" }
